//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace pr7_4._0
{
    using System;
    using System.Collections.Generic;
    
    public partial class PurchaseOrders
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PurchaseOrders()
        {
            this.PurchaseOrderItems = new HashSet<PurchaseOrderItems>();
        }
    
        public int Id { get; set; }
        public int PlacedAtClientCounter { get; set; }
        public int ArrivesAfterClients { get; set; }
        public bool IsDelivered { get; set; }
        public decimal TotalCost { get; set; }
        public System.DateTime CreatedAt { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PurchaseOrderItems> PurchaseOrderItems { get; set; }
    }
}
